# -*- coding: utf-8 -*-
"""Analyzing Customer Orders Using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSeke9sxIABH1ds54tGcFumgAoE8Zc2L
"""

# Analyzing Customer Orders Using Python
# Course-End Project 1

from collections import Counter

customer_names = [
    "Aisha", "Rahul", "Priya", "Arjun", "Sneha",
    "Vikram", "Neha", "Karan", "Fatima", "Rohit"
]

orders = [
    ("Aisha", "Laptop", 850, "Electronics"),
    ("Aisha", "T-Shirt", 25, "Clothing"),
    ("Rahul", "Smartphone", 650, "Electronics"),
    ("Rahul", "Jeans", 55, "Clothing"),
    ("Priya", "Headphones", 80, "Electronics"),
    ("Priya", "Coffee Maker", 70, "Home Essentials"),
    ("Arjun", "T-Shirt", 30, "Clothing"),
    ("Arjun", "Blender", 45, "Home Essentials"),
    ("Sneha", "Smartwatch", 120, "Electronics"),
    ("Sneha", "Jeans", 60, "Clothing"),
    ("Vikram", "Microwave", 180, "Home Essentials"),
    ("Vikram", "Headphones", 75, "Electronics"),
    ("Neha", "Dress", 90, "Clothing"),
    ("Neha", "Vacuum Cleaner", 140, "Home Essentials"),
    ("Karan", "Keyboard", 40, "Electronics"),
    ("Karan", "Mouse", 20, "Electronics"),
    ("Fatima", "Sofa Cushion", 35, "Home Essentials"),
    ("Fatima", "T-Shirt", 20, "Clothing"),
    ("Rohit", "Tablet", 300, "Electronics"),
    ("Rohit", "Backpack", 45, "Clothing"),
]

# Dictionary: customer -> ordered products
customer_orders = {customer: [] for customer in customer_names}
for customer, product, price, category in orders:
    customer_orders[customer].append(product)

# Dictionary: product -> category

product_categories = {
    "Laptop": "Electronics", "T-Shirt": "Clothing",
    "Smartphone": "Electronics", "Jeans": "Clothing",
    "Headphones": "Electronics", "Coffee Maker": "Home Essentials",
    "Blender": "Home Essentials", "Smartwatch": "Electronics",
    "Microwave": "Home Essentials", "Dress": "Clothing",
    "Vacuum Cleaner": "Home Essentials", "Keyboard": "Electronics",
    "Mouse": "Electronics", "Sofa Cushion": "Home Essentials",
    "Tablet": "Electronics", "Backpack": "Clothing",
}

categories = set(product_categories.values())

# Customer spending and classification
customer_spending = {}
for customer in customer_names:
    total = 0
    for order_customer, product, price, category in orders:
        if order_customer == customer:
            total += price
    customer_spending[customer] = total

customer_classification = {}
for customer, total in customer_spending.items():
    if total > 100:
        customer_classification[customer] = "High-value buyer"
    elif 50 <= total <= 100:
        customer_classification[customer] = "Moderate buyer"
    else:
        customer_classification[customer] = "Low-value buyer"

# Category-wise revenue
category_revenue = {category: 0 for category in categories}
for customer, product, price, category in orders:
    category_revenue[category] += price

# Unique products
unique_products = set(product for customer, product, price, category in orders)

# List/set comprehension: electronics customers
electronics_customers = list({
    customer for customer, product, price, category in orders
    if category == "Electronics"
})

# Top three customers
top_three_customers = sorted(
    customer_spending.items(),
    key=lambda item: item[1],
    reverse=True
)[:3]

# Product frequency
product_frequency = Counter(product for customer, product, price, category in orders)

# Customers by category
customers_by_category = {}
for category in categories:
    customers_by_category[category] = {
        customer for customer, product, price, order_category in orders
        if order_category == category
    }

# Multiple-category customers
multi_category_customers = set()
for customer in customer_names:
    customer_categories = {
        category for order_customer, product, price, category in orders
        if order_customer == customer
    }
    if len(customer_categories) > 1:
        multi_category_customers.add(customer)

# Electronics AND Clothing
electronics_and_clothing = (
    customers_by_category["Electronics"]
    & customers_by_category["Clothing"]
)

# Dictionary modification example
customer_orders["Aisha"].append("Phone Case")
product_categories["Phone Case"] = "Electronics"

# Output
print("\nCUSTOMER SPENDING AND CLASSIFICATION")
for customer in customer_names:
    print(
        f"{customer}: ${customer_spending[customer]:.2f} - "
        f"{customer_classification[customer]}"
    )

print("\nCATEGORY-WISE REVENUE")
for category, revenue in sorted(
    category_revenue.items(), key=lambda x: x[1], reverse=True
):
    print(f"{category}: ${revenue:.2f}")

print("\nUNIQUE PRODUCTS")
print(sorted(unique_products))

print("\nELECTRONICS CUSTOMERS")
print(sorted(electronics_customers))

print("\nTOP 3 CUSTOMERS")
for rank, (customer, amount) in enumerate(top_three_customers, start=1):
    print(f"{rank}. {customer}: ${amount:.2f}")

print("\nMOST FREQUENT PRODUCTS")
for product, count in product_frequency.most_common():
    print(f"{product}: {count}")

print("\nMULTI-CATEGORY CUSTOMERS")
print(sorted(multi_category_customers))

print("\nELECTRONICS AND CLOTHING CUSTOMERS")
print(sorted(electronics_and_clothing))