# -*- coding: utf-8 -*-
"""Python Adventure Game with GitHub Copilot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjXd2M8m7cLPujlUXeQ95CnglT7KoVLK
"""

# Text-based adventure game using Python and GitHub Copilot assistance.

def forest_path(player_name):
    """Handle the forest adventure and return True if the player wins."""
    print("\nYou enter the dark forest.")
    print("You hear a river nearby and see a tall tree.")
    print("1. Follow the river")
    print("2. Climb the tree")

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == "1":
        print("\nYou follow the river and discover an old bridge.")
        print("Under the bridge, you find a treasure chest!")
        print(f"Congratulations, {player_name}! You found the legendary treasure!")
        return True
    elif choice == "2":
        print("\nYou climb the tree, but a strong branch breaks.")
        print("You fall safely but lose your map and cannot continue.")
        print("The adventure ends.")
        return False
    else:
        print("\nInvalid choice. You get lost in the forest.")
        print("The adventure ends.")
        return False

def cave_path(player_name):
    """Handle the cave adventure and return True if the player wins."""
    print("\nYou enter the mysterious cave.")
    print("It is very dark, and you have two options.")
    print("1. Light a torch")
    print("2. Proceed in the dark")

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == "1":
        print("\nThe torch lights the cave.")
        print("You discover a hidden passage leading to a treasure room!")
        print(f"Congratulations, {player_name}! You found the legendary treasure!")
        return True
    elif choice == "2":
        print("\nYou walk in the dark and fall into a hidden pit.")
        print("The adventure ends.")
        return False
    else:
        print("\nInvalid choice. You cannot find your way through the cave.")
        print("The adventure ends.")
        return False

def start_game():
    """Start one complete adventure and return whether the player won."""
    print("\n" + "=" * 45)
    print("        THE LEGENDARY TREASURE")
    print("=" * 45)
    print("You are an explorer searching for a legendary treasure.")
    print("Choose your path carefully to complete the quest.")

    player_name = input("\nEnter your name: ").strip()
    if not player_name:
        player_name = "Explorer"

    print(f"\nWelcome, {player_name}!")
    print("Where would you like to go?")
    print("1. Explore the dark forest")
    print("2. Enter the mysterious cave")

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == "1":
        return forest_path(player_name)
    elif choice == "2":
        return cave_path(player_name)
    else:
        print("\nInvalid choice. You lose your way.")
        return False

def main():
    """Run the game repeatedly until the player chooses to stop."""
    while True:
        won = start_game()

        if won:
            print("\nQuest completed successfully!")
        else:
            print("\nQuest failed. You can try again.")

        restart = input("\nWould you like to play again? (yes/no): ").strip().lower()
        if restart not in ("yes", "y"):
            print("\nThank you for playing. Goodbye!")
            break


if __name__ == "__main__":
    main()

